### PR TITLE
PDF Viewer (using PDF.js)

### PR DESCRIPTION
**Pull request by jkeck**
pdf-viewer

## TODO
_Estimate 2 devs could complete w/i a day (potentially shorter if coupled w/ #1050 as some similar work will end up happening there)_
- [x] Tests
- [x] Use legit buttons
- [x] Update pdf viewer JS to match current patterns
- [x] Handle failure state
- [x]  Handle footer buttons/panels
  - [x] Download
  - [x] Embed This
  - [x] Full screen

### CODE REVIEW

**Comment by mejackreed** [comment]
@jkeck one quick question I had was about the committing of the `pdf_worker.js` file. Is that file vendor generated file or is that something our build creates?

**Comment by jkeck** [comment]
It's a vendor created file (generated and shipped w/ PDF.js)

**Comment by mejackreed** [comment]
Is it something we can import/require into that file that so that we don't have to check it in? Or are we SOL on that.

**Comment by jkeck** [comment]
Not that I'm aware of.  The worker needs to be available at a URL AFAICT.

**Comment by camillevilla** [comment]
Nice work, @jkeck. I did notice that the focus styles for keyboard tab navigation don't seem to be working in Firefox (but work fine for Chrome and Safari). Is this already an known issue upstream? Or is there something about our styling that isn't being supported in Firefox? 

## Chrome
tabs-chrome

## Firefox
tabs-firefox

**Comment by camillevilla** [comment]
Neeeeevermind. That's just a fundamental difference between Firefox and Chrome's default focus styles. 😭 The reason I noticed this is that UV augments overrides browser focus styles with its own. That's why you can still see the purple focus outline in Firefox on UV:

## UV
focus-styles

**Comment by jvine** [comment]
Just some notes from poking at the focus indicator issue, no impact on this PR:  The Firefox focus issue is well-known, and it's "legal" to leave it as-is. Any explicit focus outline that would make Firefox's focus visible on black would also change the default behaviour for all other browsers. It's not possible to replicate Chrome's focus outline on other browsers. Related: it's not clear why we have overridden default focus behaviour on the embed frame.

**Comment by anarchivist** [comment]
@jkeck A couple of lingering issues, which relate to `world (no download)` and `location: spec` objects:

* `location: spec`: bd742gh0511 - you just get a blank display, no error message
* `world (no-download)`: bd989qy8176, bf177xm2396

**Comment by jkeck** [comment]
## Generic error (no-download) bd989qy8176
generic-no-download-bd989qy8176

## Location restricted error bd742gh0511
location-restricted-bd742gh0511

**Pull request merged**
