### PR TITLE
specify default_body_height for image_x viewer, which fixes embed pan…

### PR DESCRIPTION
**Pull request by mejackreed**
…el bugs

### CODE REVIEW

**Comment by aeschylus** [comment]
It clearly does, but how does this fix the width as well? Is the height is used to calculate the width somewhere?

**Comment by mejackreed** [comment]
That happens here: https://github.com/sul-dlss/sul-embed/blob/master/lib/embed/viewer/common_viewer.rb#L203

**Comment by mejackreed** [comment]
And by default width is `nil`: https://github.com/sul-dlss/sul-embed/blob/master/lib/embed/viewer/common_viewer.rb#L338

**Comment by aeschylus** [comment]
Okay, I see that now. I didn't see where the height was coming from. So it just becomes a square by default. Seems reasonable.

**Pull request merged**
