### PR TITLE
Apply hover color to media content items

### LINKED ISSUE #1969: Add selection indicator for media content items
Currently, there is no visual indicator when selecting an item within the media contents.
Toggle style `box-shadow: 0px 0px 3px 2px #016895` on the selected item.
Note: `#016895` is [SU sky dark](https://identity.stanford.edu/design-elements/color/accent-colors/) and the gradient satisfies the [WCAG color contrast ratio](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance.html#change-of-contrast-gradients).

### PR DESCRIPTION
**Pull request by mjgiarlo**
Fixes #1969

This commit adds a visual style when the user hovers over media content items, letting them know which is currently being acted upon.

Screenshot from 2023-12-13 14-12-13

### CODE REVIEW

**Review by aaron-collier — APPROVED** [review]

**Review by hudajkhan — APPROVED** [review]
Works in Chrome

**Review by jcoyne — COMMENTED** [review]
wasn't the point of the ticket for the style to be on the active item?

**Comment by mjgiarlo** [comment]
@jcoyne Could be? Depends on what is meant by "selected."

@alundgard should the shadow box be on the item displayed in the main part of the viewer, or the item the user is hovering over in the companion window? I interpreted "selected" as the latter. If we really want the former, I can make that change, and I'd also be curious if we want any hover behaviors (regardless of what's currently displayed).

**Comment by alundgard** [comment]
The former: the shadow box should be applied to the item currently displayed in the viewer. (My bad for not explaining this clearly in #1969.) The idea is to have an indicator that disambiguates between multiple visually-redundant items, as in [this example](https://sul-purl-uat.stanford.edu/bb142ws0723). I don't think we need any styling on hover; the `cursor: pointer` is enough of an indicator that the media item is clickable.

**Comment by mjgiarlo** [comment]
@alundgard OK, I'll pick this back up, no problem. Thanks!

**Comment by alundgard** [comment]
Thanks @mjgiarlo ! While you're in that vicinity, I'm also seeing some new visual cruft on the media items. Unsure if this is related or not. If not, I can make a separate ticket.
media-item-cruft

**Comment by mjgiarlo** [comment]
@alundgard AFAICT, it's not related, but I could be mistaken. A new ticket would be grand.

**Pull request merged**
