### PR TITLE
Keyboard access

### LINKED ISSUE #143: Add keyboard navigation to image viewer views

### LINKED ISSUE #427: Keyboard control navigation

### PR DESCRIPTION
**Pull request by mejackreed**
Closes #427 , closes #143 

Adds support for basic left/right navigation in the following contexts:

context | key | action
---------- | ----- | -------
`bottomPanelOpen` | left | previous image
`bottomPanelOpen` | right | next image
`bottomPanelClosed` | left, right | no action
`overview perspective` | left | previous image
`overview perspective` | right | next image

These contexts are extendable and should be able to easily meet usability enhancement goals.

### CODE REVIEW

**Comment by mejackreed** [comment]
As far as I can tell, all of the hound violations are coming from the vendor javascript which should be ignored (but is not by hound :cry: ) :dog:

**Comment by aeschylus** [comment]
Awesome. Why would the keyboard commands be different if the bottom panel is closed though? Is this when we would switch over to the osd canvas controls (panning instead of nexting)? Seems reasonable, but might confuse some people. I think we might eventually add another context for when the osd canvas is zoomed below its home bounds to use for that purpose.

**Comment by jkeck** [comment]
Not sure if this helps but checkout 

https://github.com/sul-dlss/sul-requests/blob/master/.hound.yml#L11
https://github.com/sul-dlss/sul-requests/blob/master/.javascript_ignore

**Comment by mejackreed** [comment]
Thanks @jkeck it worked!

**Comment by mejackreed** [comment]
@aeschylus yep agree on the second context that is needed. I wrote it this way so we could easily extend the behavior to accommodate that or any other context. I'm figuring that there will be modifications that need to happen at some point.

**Pull request merged**
