### PR TITLE
Tilesource and overlays fixes

### PR DESCRIPTION
**Pull request by aeschylus**

### CODE REVIEW

**Comment by aeschylus** [comment]
Hm, seems to pass everything in CI.

**Comment by mejackreed** [comment]
:+1: can we rebase down all of these into 1 commit? Or just make a clean commit that does the manifestor update? I'm not sure why e7ab123 is included here?

**Comment by mejackreed** [comment]
Doing the manifestor update on another branch/pr is fine too

**Comment by aeschylus** [comment]
Hm, neither am I. I'll make it in another branch.

**Pull request closed without merging**
