### PR TITLE
UV provides its own header and footer

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by mejackreed** [comment]
Were you seeing issues in the viewer without this?

**Comment by cbeer** [comment]
Yes -- without this, the bottom 30 pixels that should be used by the viewer were blank, making it awkward to do https://github.com/sul-dlss/exhibits/issues/1063 (the iframe is 600px, the viewer was only 570px)

**Comment by mejackreed** [comment]
Nice, great catch. Just was wondering :)

**Comment by cbeer** [comment]
screen shot 2018-01-30 at 16 18 41

**Pull request merged**
