### PR TITLE
Add a simple rack app to stub the Stacks auth endpoint...

### LINKED ISSUE #567: Write integration test for Media Auth Link
We do not have a good way of stubbing an external URL request made via JS in our integration tests.

Since the relevant Stacks code is not in production yet, we cannot write an integration test around the log-in links for media.  Once it has been deployed, we can do that much easier.

### PR DESCRIPTION
**Pull request by jkeck**
...and include some integration tests for the WebAuth login link being shown or hidden.

Closes #567

### CODE REVIEW

**Comment by ndushay** [comment]
So what would other alternatives be?  Here's what I can think of:

* mocking the stacks calls and what is returned using rspec mocks / webmock 
* VCR cassettes for the stacks calls

other options?

**Comment by jkeck** [comment]
Yeah, that's pretty much the alternative, and the dependencies this is attempting to avoid introducing.

**Comment by ndushay** [comment]
I'm wondering if we can do mocks reasonably well with less complexity.  Maybe i'll give it a shot in a separate branch.

**Comment by ndushay** [comment]
hahaha - ok, my short experiment was a colossal failure, as @jkeck no doubt expected.

**Comment by jmartin-sul** [comment]
i like this.

is this better than than webmock?  neither approach seems clearly better than the other to me at first glance.  i'd be happy to merge this, if only to see how its maintainability compares to webmock's as development continues.

but this approach and webmock are both greatly preferable to VCR, IMO.  definite 👍 for a non-vcr solution.

**Comment by ndushay** [comment]
@jmartin-sul webmock won't work, as I empirically discovered, because the request is coming from javascript, not from ruby.

**Comment by jmartin-sul** [comment]
ah, yeah, of course.

**Pull request merged**
