### PR TITLE
Update to rails 6

### PR DESCRIPTION
**Pull request by jkeck**
I'm getting a flapping geo viewer spec that's also failing for me on master.

### CODE REVIEW

**Comment by cbeer** [comment]
Do you know if we need to add `skip_forgery_protection` to the JSON endpoints?

**Comment by jkeck** [comment]
@cbeer I don't think that would be necessary for this app (but perhaps I'm not thinking of somewhere that would be helpful).

Is there a rails 6 changes WRT `skip_forgery_protection` that I should be keeping an eye on?

**Comment by cbeer** [comment]
I'm not sure; I just remember we've been burned by it a couple times now.

**Comment by jkeck** [comment]
Oddly the docs say that the change was to move the `default_protect_from_forgery` config `ActionController::Base` but it was kept `false` by default. Although our setup is similar to stacks where I believe we've run into this before, (e.g. no explicit `protect_from_forgery` call) things _seem_ to be working out (I deployed this to UAT).

I'm happy to add `skip_forgery_protection` to the. places where we might need it in case we want to be extra cautious.

**Pull request merged**
