### PR TITLE
change current view to zoomed region text

### LINKED ISSUE #807: Download link text is confusing
Testing : https://sul-purl-uat.stanford.edu/bc421tk1152 in Chrome on Mac

The download link text is confusing.  Maybe "Current View" can be changed to something like "Zoomed region only" or something.  Was also a little confused by two links that said "Whole Image" but with different sizes.  

Interested in @jvine and @ggeisler thoughts on this.  

image

### PR DESCRIPTION
**Pull request by mejackreed**
Closes #807 

cc @ggeisler 

screen shot 2017-08-22 at 5 11 04 pm

### CODE REVIEW

**Comment by ggeisler** [comment]
Any objection to adding a colon after "Zoomed region" and "Whole image", as in my mockup in #807?

**Comment by mejackreed** [comment]
Missed that.. @ggeisler I'll add those in. Thanks for catching that.

**Comment by mejackreed** [comment]
Updated cc @ggeisler 

screen shot 2017-08-22 at 7 07 45 pm

**Comment by mejackreed** [comment]
And more options here: https://github.com/UniversalViewer/universalviewer/blob/v3/src/extensions/uv-seadragon-extension/l10n/en-GB.json#L48-L67

**Comment by ggeisler** [comment]
Thanks @mejackreed. Not sure if I'm misunderstanding something but your updated screenshot only shows the colon after "Zoomed region". I think we'd want it after all labels, or none of them.

**Comment by mejackreed** [comment]
Akk. you're right! Looks like UV isn't respecting that config. I've reverted back to no colon and we can come back to this later.

**Pull request merged**
