### PR TITLE
Several rubocop inspired changes that could not be autofixed

### PR DESCRIPTION
**Pull request by jkeck**
(just trying to get things removed out of the `todo.yml` while I have some spare time)

### CODE REVIEW

**Comment by aeschylus** [comment]
I think this can be merged once we get around to fixing the auth tests (separate issue).

**Comment by ndushay** [comment]
:+1: for merge

**Comment by ndushay** [comment]
@jmartin-sul and I were thinking of whacking at rubocop stuff to familiarize ourselves a bit with the code.  Can this PR be merged as is (before fixing auth tests)  so we can proceed easily?   We'll branch off this for now but ...

**Comment by mejackreed** [comment]
:ship_it:

**Pull request merged**
