### PR TITLE
update js, css to indicate when pdf is selected

### LINKED ISSUE #2161: (new pdf viewer) Clearly indicate which PDF is selected when there are multiple PDFs
The left companion window should indicate which document has been selected when there are multiple PDFs. Currently, you can't tell which PDF you are viewing.

Screenshot 2024-06-03 at 10 12 00 AM

### PR DESCRIPTION
**Pull request by dnoneill**
closes #2161 

Based on @alundgard comments updated to be 
Screenshot 2024-06-06 at 10 46 12 AM

### CODE REVIEW

**Comment by peetucket** [comment]
Nice.  Not really my call, but maybe bolded too would make it even more obvious?

**Comment by alundgard** [comment]
Since there isn't a non-color visual indicator of active state, I believe the active state color will need a 3:1 contrast ratio with both the background (white) and the inactive state color (black). https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast#user-interface-components

**Review by peetucket — APPROVED** [review]
Approved pending PO approval.

**Comment by alundgard** [comment]
> Approved pending PO approval.

Approved here: https://github.com/sul-dlss/sul-embed/issues/2161#issuecomment-2152950467

**Pull request merged**
