### PR TITLE
[WIP] Swap webpacker for bower-rails

### PR DESCRIPTION
**Pull request by jcoyne**
webpacker is an official rails project and I anticipate it'll get more
support than bower-rails in the future.

I'm having a curious problem now where:
```
 LayoutStore is not defined
```
This is occuring because `ImageXViewer` is depending on this as a global.

### CODE REVIEW

**Comment by jcoyne** [comment]
@aeschylus @mejackreed do you know anything about this `LayoutStore is not defined`? Should I be using https://github.com/webpack/docs/wiki/list-of-plugins#provideplugin ?

**Comment by jcoyne** [comment]
@aeschylus @mejackreed alternatively, is it okay to refactor LayoutStore to `export default LayoutStore = function(options) { ... }`?

**Comment by csbailey5t** [comment]
@jcoyne In the new standard JS way, `export default LayoutStore` should work for when you import that file with a generic import, such as `import 'modules/layout_store';` as long as that is the only function you want to export from the file. You could also try a partial import, such as `import LayoutStore from 'modules/layout_store';`.

**Comment by mejackreed** [comment]
Yeah @jcoyne i think that will be fine

**Comment by mejackreed** [comment]
One thing we haven't addressed here yet is the deployment story. Just adding a comment here as a reminder to test that.

**Comment by jkeck** [comment]
This has been completed in another PR.

**Pull request closed without merging**
